ALTER TABLE T_BOOKS
ADD COLUMN IF NOT EXISTS CREATED_AT TIMESTAMP,
ADD COLUMN IF NOT EXISTS CREATED_BY VARCHAR,
ADD COLUMN IF NOT EXISTS UPDATED_AT TIMESTAMP,
ADD COLUMN IF NOT EXISTS UPDATED_BY TIMESTAMP;

INSERT INTO T_BOOKS("book_name") VALUES('HEAD FIRST JAVA');